In [1]:
import numpy as np

#### Q1- Generate 100 random integers from 0-10 and count each integer came how many times

In [2]:
# genetrating an array
arr = np.random.randint(0,11,100)
arr

array([ 7,  8,  5,  7,  0,  3,  1,  5,  6, 10, 10,  5,  1,  4,  3,  9,  7,
        8,  6,  1,  0,  5, 10,  6,  6,  3,  6,  3, 10,  0,  4,  3,  0,  9,
        0,  7,  3,  7,  1,  0, 10,  6,  5,  8, 10,  5,  3,  4,  5,  3,  1,
        3,  8,  7,  6, 10,  8,  5,  8,  7,  9,  4,  9,  3, 10,  3,  5,  8,
        7,  9,  3,  5,  8, 10,  3,  2,  7,  0,  8,  8,  8,  6,  9,  4,  9,
        6,  1,  7,  2,  7,  6,  4,  3,  6,  3,  0,  2, 10,  3, 10])

In [3]:
# now we filter each number and its count using masking througha for loop

for i in range(0,11):
    filtered_array = arr[arr == i]
    count= filtered_array.size
    print(f"The count of {i} is:{count}")

The count of 0 is:8
The count of 1 is:6
The count of 2 is:3
The count of 3 is:16
The count of 4 is:6
The count of 5 is:10
The count of 6 is:11
The count of 7 is:11
The count of 8 is:11
The count of 9 is:7
The count of 10 is:11


#### Q2- Now from Q1 make an array of even numbers and their mean

In [4]:
even_numbers = arr[arr%2 == 0]
mean_ =even_numbers.mean()
mean_

np.float64(5.88)

#### Q-3 Now categorize Q1 array in three categories low(0-3) medium(4-7) high(8-10)

In [5]:
low = arr[arr<=3]
low.size

33

In [6]:
medium = arr[(arr>= 4) & (arr<=7)]
medium.size

38

In [7]:
high = arr[(arr>= 8) & (arr<=10)]
high.size

29

#### Q-4 Normaliz between 0-1

In [8]:
min_val = arr.min()
max_val = arr.max()
normalized_arr = (arr - min_val)/(max_val-min_val)
normalized_arr

array([0.7, 0.8, 0.5, 0.7, 0. , 0.3, 0.1, 0.5, 0.6, 1. , 1. , 0.5, 0.1,
       0.4, 0.3, 0.9, 0.7, 0.8, 0.6, 0.1, 0. , 0.5, 1. , 0.6, 0.6, 0.3,
       0.6, 0.3, 1. , 0. , 0.4, 0.3, 0. , 0.9, 0. , 0.7, 0.3, 0.7, 0.1,
       0. , 1. , 0.6, 0.5, 0.8, 1. , 0.5, 0.3, 0.4, 0.5, 0.3, 0.1, 0.3,
       0.8, 0.7, 0.6, 1. , 0.8, 0.5, 0.8, 0.7, 0.9, 0.4, 0.9, 0.3, 1. ,
       0.3, 0.5, 0.8, 0.7, 0.9, 0.3, 0.5, 0.8, 1. , 0.3, 0.2, 0.7, 0. ,
       0.8, 0.8, 0.8, 0.6, 0.9, 0.4, 0.9, 0.6, 0.1, 0.7, 0.2, 0.7, 0.6,
       0.4, 0.3, 0.6, 0.3, 0. , 0.2, 1. , 0.3, 1. ])

#### Q-5 Now extract 3 most frequent elements of array

In [9]:
unique_elements, counts = np.unique(arr, return_counts=True)
top3 = np.argsort(counts)[-3:]
top3_elements = unique_elements[top3]
print(top3_elements)

[10  8  3]


#### Q-6 now reshape the array in 10x10 metrics

In [10]:
met =arr.reshape(10,10)
met

array([[ 7,  8,  5,  7,  0,  3,  1,  5,  6, 10],
       [10,  5,  1,  4,  3,  9,  7,  8,  6,  1],
       [ 0,  5, 10,  6,  6,  3,  6,  3, 10,  0],
       [ 4,  3,  0,  9,  0,  7,  3,  7,  1,  0],
       [10,  6,  5,  8, 10,  5,  3,  4,  5,  3],
       [ 1,  3,  8,  7,  6, 10,  8,  5,  8,  7],
       [ 9,  4,  9,  3, 10,  3,  5,  8,  7,  9],
       [ 3,  5,  8, 10,  3,  2,  7,  0,  8,  8],
       [ 8,  6,  9,  4,  9,  6,  1,  7,  2,  7],
       [ 6,  4,  3,  6,  3,  0,  2, 10,  3, 10]])

#### Q-7 Now find sum of all rows and >50

In [11]:
sum_of_rows = np.sum(met, axis=1)
sum_of_rows

array([52, 54, 49, 34, 59, 63, 67, 54, 59, 47])

In [12]:
sum_of_rows[sum_of_rows>= 50]

array([52, 54, 59, 63, 67, 54, 59])

In [13]:
indecies = np.where(sum_of_rows>= 50)
indecies

(array([0, 1, 4, 5, 6, 7, 8]),)

#### Q-8 Now find mean of all col and mean of highest mean index

In [14]:
mean_of_col = np.mean(met, axis=0)
mean_of_col

array([5.8, 4.9, 5.8, 6.4, 5. , 4.8, 4.3, 5.7, 5.6, 5.5])

In [15]:
highest_pos= mean_of_col.argmax()
print(f"The highest index of mean is: {highest_pos}")

The highest index of mean is: 3


#### Q-8 sum of diaglonals

In [16]:
diagonal= np.diag(met)
sum_of_diagonal = np.sum(diagonal)
print(f"Sum of Diagonal is: {sum_of_diagonal}" )

Sum of Diagonal is: 68


#### Q-10 Normalize array row wise and so each row sum is 1

In [17]:
met

array([[ 7,  8,  5,  7,  0,  3,  1,  5,  6, 10],
       [10,  5,  1,  4,  3,  9,  7,  8,  6,  1],
       [ 0,  5, 10,  6,  6,  3,  6,  3, 10,  0],
       [ 4,  3,  0,  9,  0,  7,  3,  7,  1,  0],
       [10,  6,  5,  8, 10,  5,  3,  4,  5,  3],
       [ 1,  3,  8,  7,  6, 10,  8,  5,  8,  7],
       [ 9,  4,  9,  3, 10,  3,  5,  8,  7,  9],
       [ 3,  5,  8, 10,  3,  2,  7,  0,  8,  8],
       [ 8,  6,  9,  4,  9,  6,  1,  7,  2,  7],
       [ 6,  4,  3,  6,  3,  0,  2, 10,  3, 10]])

In [18]:
rows_sum = met.sum(axis = 1)
rows_sum

array([52, 54, 49, 34, 59, 63, 67, 54, 59, 47])

In [19]:
rows_sum =rows_sum[:, np.newaxis]
rows_sum

array([[52],
       [54],
       [49],
       [34],
       [59],
       [63],
       [67],
       [54],
       [59],
       [47]])

In [20]:
norm = met/ rows_sum
norm

array([[0.13461538, 0.15384615, 0.09615385, 0.13461538, 0.        ,
        0.05769231, 0.01923077, 0.09615385, 0.11538462, 0.19230769],
       [0.18518519, 0.09259259, 0.01851852, 0.07407407, 0.05555556,
        0.16666667, 0.12962963, 0.14814815, 0.11111111, 0.01851852],
       [0.        , 0.10204082, 0.20408163, 0.12244898, 0.12244898,
        0.06122449, 0.12244898, 0.06122449, 0.20408163, 0.        ],
       [0.11764706, 0.08823529, 0.        , 0.26470588, 0.        ,
        0.20588235, 0.08823529, 0.20588235, 0.02941176, 0.        ],
       [0.16949153, 0.10169492, 0.08474576, 0.13559322, 0.16949153,
        0.08474576, 0.05084746, 0.06779661, 0.08474576, 0.05084746],
       [0.01587302, 0.04761905, 0.12698413, 0.11111111, 0.0952381 ,
        0.15873016, 0.12698413, 0.07936508, 0.12698413, 0.11111111],
       [0.13432836, 0.05970149, 0.13432836, 0.04477612, 0.14925373,
        0.04477612, 0.07462687, 0.11940299, 0.10447761, 0.13432836],
       [0.05555556, 0.09259259, 0.1481481

In [21]:
norm.sum(axis =1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Q-11 convert metrics into binary 5= 1 and 0 others

In [22]:
met

array([[ 7,  8,  5,  7,  0,  3,  1,  5,  6, 10],
       [10,  5,  1,  4,  3,  9,  7,  8,  6,  1],
       [ 0,  5, 10,  6,  6,  3,  6,  3, 10,  0],
       [ 4,  3,  0,  9,  0,  7,  3,  7,  1,  0],
       [10,  6,  5,  8, 10,  5,  3,  4,  5,  3],
       [ 1,  3,  8,  7,  6, 10,  8,  5,  8,  7],
       [ 9,  4,  9,  3, 10,  3,  5,  8,  7,  9],
       [ 3,  5,  8, 10,  3,  2,  7,  0,  8,  8],
       [ 8,  6,  9,  4,  9,  6,  1,  7,  2,  7],
       [ 6,  4,  3,  6,  3,  0,  2, 10,  3, 10]])

In [23]:
binary_metrics = np.where(met == 5,1,0)
binary_metrics

array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### Q-12 calculate the average of sliding windows 3x3 

In [24]:
rows, col = met.shape
output = np.zeros((rows-2, col-2))
for i in range(0, rows-2): 
    for j in range(0, col-2):
        windows = met[i: i+3, j:j+3]
        avg= windows.mean()
        output[i,j]= avg
print(output)

[[5.66666667 5.66666667 4.66666667 4.55555556 4.22222222 5.
  5.77777778 5.44444444]
 [4.22222222 4.77777778 4.33333333 5.22222222 4.88888889 5.88888889
  5.66666667 4.        ]
 [4.77777778 5.77777778 6.         6.         4.77777778 4.55555556
  4.66666667 3.66666667]
 [4.44444444 5.44444444 5.88888889 6.88888889 5.77777778 5.77777778
  4.88888889 4.44444444]
 [6.11111111 5.88888889 7.33333333 6.88888889 6.66666667 5.66666667
  5.88888889 6.22222222]
 [5.55555556 6.33333333 7.11111111 6.         6.         5.33333333
  6.22222222 6.66666667]
 [6.77777778 6.44444444 7.22222222 5.55555556 5.11111111 4.33333333
  5.         6.22222222]
 [5.77777778 6.11111111 6.11111111 4.77777778 3.66666667 3.88888889
  4.44444444 6.11111111]]


In [25]:
maxout = np.zeros((rows-2, col-2))
for i in range(0, rows-2):
    for j in range(0, col-2):
        window= met[i: i+2, j:j+2]
        maxval = window.max()
        maxout[i,j] = maxval
print(maxout)

[[10.  8.  7.  7.  9.  9.  8.  8.]
 [10. 10. 10.  6.  9.  9.  8. 10.]
 [ 5. 10. 10.  9.  7.  7.  7. 10.]
 [10.  6.  9. 10. 10.  7.  7.  7.]
 [10.  8.  8. 10. 10. 10.  8.  8.]
 [ 9.  9.  9. 10. 10. 10.  8.  8.]
 [ 9.  9. 10. 10. 10.  7.  8.  8.]
 [ 8.  9. 10. 10.  9.  7.  7.  8.]]


In [26]:
let= maxout[0:, 6:]
let

array([[ 8.,  8.],
       [ 8., 10.],
       [ 7., 10.],
       [ 7.,  7.],
       [ 8.,  8.],
       [ 8.,  8.],
       [ 8.,  8.],
       [ 7.,  8.]])

In [27]:
let.sum(axis=0)

array([61., 67.])

#### Q-13 Correlation

In [28]:
row1= let[0]
row2 = let[1]
corr = np.corrcoef(row1, row2)[0,1]
print(corr)

nan


/opt/anaconda3/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/opt/anaconda3/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


In [29]:
data = np.array([
    [2, 3, 4, 5, 6, 5, 7],   # study hours
    [5, 6, 7, 8, 9, 8, 10]  # social media usage
])
data

array([[ 2,  3,  4,  5,  6,  5,  7],
       [ 5,  6,  7,  8,  9,  8, 10]])

In [30]:
row1 = data[0]
row2= data[1]
correlation = np.corrcoef(row1, row2)[0,1]
print(correlation)
# Comment / Interpretation:
# The correlation value is 1.0, which is a perfect positive correlation.
# This means that as study hours increase, social media usage also increases.
# Positive correlation → both variables move in the same direction
# Negative correlation → one increases, the other decreases
# Value close to 0 → no linear relationship

1.0


#### Q-14 Outlier 

In [31]:
data = np.array([
    [45, 48, 50],
    [47, 49, 60],
    [46, 48, 47],
    [49, 50, 48]
])

In [32]:
mean = data.mean()
std = data.std()
lower = mean - 2*std
upper = mean + 2*std
outlier = data[(data<lower) | (data> upper)]
print(outlier)

[60]


In [33]:
met

array([[ 7,  8,  5,  7,  0,  3,  1,  5,  6, 10],
       [10,  5,  1,  4,  3,  9,  7,  8,  6,  1],
       [ 0,  5, 10,  6,  6,  3,  6,  3, 10,  0],
       [ 4,  3,  0,  9,  0,  7,  3,  7,  1,  0],
       [10,  6,  5,  8, 10,  5,  3,  4,  5,  3],
       [ 1,  3,  8,  7,  6, 10,  8,  5,  8,  7],
       [ 9,  4,  9,  3, 10,  3,  5,  8,  7,  9],
       [ 3,  5,  8, 10,  3,  2,  7,  0,  8,  8],
       [ 8,  6,  9,  4,  9,  6,  1,  7,  2,  7],
       [ 6,  4,  3,  6,  3,  0,  2, 10,  3, 10]])

In [34]:
mean = met.mean(axis=1)
std = met.std(axis=1)
lower = mean - 2*std
upper = mean + 2*std
outlier = met[(met<lower[:, None]) | (met > upper[:, None])]
print(outlier)

[1]


#### Q-15 Treat a metrics Rows as a sample and coulmn as a feature calculate mean and std feature wise

In [35]:
feat_mean = met.mean(axis=0)
feat_std= met.std(axis=0)
print(feat_mean)
print(feat_std)

[5.8 4.9 5.8 6.4 5.  4.8 4.3 5.7 5.6 5.5]
[3.45832329 1.44568323 3.37045991 2.15406592 3.60555128 3.02654919
 2.49198716 2.75862284 2.72763634 3.87943295]


#### Q-17 Make a target var in dataset row sum > threshold → label = 1 else label =0 

In [38]:
met

array([[ 7,  8,  5,  7,  0,  3,  1,  5,  6, 10],
       [10,  5,  1,  4,  3,  9,  7,  8,  6,  1],
       [ 0,  5, 10,  6,  6,  3,  6,  3, 10,  0],
       [ 4,  3,  0,  9,  0,  7,  3,  7,  1,  0],
       [10,  6,  5,  8, 10,  5,  3,  4,  5,  3],
       [ 1,  3,  8,  7,  6, 10,  8,  5,  8,  7],
       [ 9,  4,  9,  3, 10,  3,  5,  8,  7,  9],
       [ 3,  5,  8, 10,  3,  2,  7,  0,  8,  8],
       [ 8,  6,  9,  4,  9,  6,  1,  7,  2,  7],
       [ 6,  4,  3,  6,  3,  0,  2, 10,  3, 10]])

In [40]:
met.sum(axis=1)
ex_met = np.where(met.sum(axis=1) > 54,1,0)
ex_met

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0])

#### Q-18 Linera model and weighted sum

In [41]:
features = [2, 4, 6]
weight = [0.8, 0.5, 0.6]

In [42]:
score = 2*0.4 + 4* 0.5 + 6*0.6
score

6.3999999999999995

#### Q19 — Sigmoid (score → probability)

In [ ]:
prob = 1/ (1+ np.exp(-6.39))
print(f"probability: {prob} ")

0.9983245556235256


Q-20

In [53]:
y_true = ex_met
y_prob = prob
thresholds = [0.2, 0.4, 0.6, 0.8]
for t in thresholds: 
    y_pred = (y_prob>=t).astype(int)
    acc = np.mean(y_pred == y_true)
    print(f"Threshold {t} : {acc}")

Threshold 0.2 : 0.4
Threshold 0.4 : 0.4
Threshold 0.6 : 0.4
Threshold 0.8 : 0.4
