In [2]:
import numpy as np

In [5]:
# simple array creation with numpy
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
# testing multiple data type in numpy array
arr=[1,2,3,"hamza"]
np.array(arr)

array(['1', '2', '3', 'hamza'], dtype='<U21')

In [7]:
# vectors are one dimensional like below
vec=[1,2,3,4,5]
vec

[1, 2, 3, 4, 5]

In [10]:
# metrics are multi dimensional like below. they are 2d 3dd andd so on
met=[[1,2,3], [4,5,6], [7,8,9]]
np.array(met)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# see the example above we gave multiple arrays in a list and numpy converted it into a metrics. That's the magic

In [12]:
# below is the example of hpw do we generate the array using arange function
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
# now let see how do we generate metrics of zero
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
# now lets generate ones
arr= np.ones((8,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
# let see how do we do linspace means linear space in py
arr= np.linspace(0,1,80)
arr

array([0.        , 0.01265823, 0.02531646, 0.03797468, 0.05063291,
       0.06329114, 0.07594937, 0.08860759, 0.10126582, 0.11392405,
       0.12658228, 0.13924051, 0.15189873, 0.16455696, 0.17721519,
       0.18987342, 0.20253165, 0.21518987, 0.2278481 , 0.24050633,
       0.25316456, 0.26582278, 0.27848101, 0.29113924, 0.30379747,
       0.3164557 , 0.32911392, 0.34177215, 0.35443038, 0.36708861,
       0.37974684, 0.39240506, 0.40506329, 0.41772152, 0.43037975,
       0.44303797, 0.4556962 , 0.46835443, 0.48101266, 0.49367089,
       0.50632911, 0.51898734, 0.53164557, 0.5443038 , 0.55696203,
       0.56962025, 0.58227848, 0.59493671, 0.60759494, 0.62025316,
       0.63291139, 0.64556962, 0.65822785, 0.67088608, 0.6835443 ,
       0.69620253, 0.70886076, 0.72151899, 0.73417722, 0.74683544,
       0.75949367, 0.7721519 , 0.78481013, 0.79746835, 0.81012658,
       0.82278481, 0.83544304, 0.84810127, 0.86075949, 0.87341772,
       0.88607595, 0.89873418, 0.91139241, 0.92405063, 0.93670

In [ ]:
# generating a  random numbers array in numpy
arr= np.random.rand(6)
arr

array([0.6306681 , 0.02820807, 0.23041917, 0.84337008, 0.56232759,
       0.74146338])

In [5]:
# generating random integers
arr= np.random.randint(10,20,10)
arr

array([[13, 18, 11, 17, 10, 13, 18, 13, 16, 17]])

In [10]:
# array attribute
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# to find rows and coulmn in array
arr.shape

(3, 3)

In [12]:
# to find the size of array
arr.size

9

In [13]:
# to find the data type
arr.dtype

dtype('int64')

In [15]:
# array methods
arr.min()

np.int64(1)

In [16]:
arr.max()

np.int64(9)

In [17]:
arr.sum()

np.int64(45)

In [18]:
# sum of col
np.sum(arr, axis=0)
# here axis define rows and coulmn if we give axis 0 it will calculate coulmn andd if we give axis 1 it will give sum of rows

array([12, 15, 18])

In [19]:
# sum of rows
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [20]:
# to find the mean
arr.mean()

np.float64(5.0)

In [21]:
# to findd the standard deviation
arr.std()

np.float64(2.581988897471611)

In [22]:
# Reshape and resizing of array
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
# reshaping of array
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
# resize
arr= arr.reshape(6,5)
arr

# so we have save the reshape array in same arr variable to its calledd resizing of array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])