In [38]:
import numpy as np

## Array operations

### Arithmatic operations

In [39]:
a1 = np.array([1,2,4,6,8,10])
a2 = np.array([1,3,5,7,9,11])
a1+a2

array([ 2,  5,  9, 13, 17, 21])

In [40]:
a1-a2

array([ 0, -1, -1, -1, -1, -1])

In [41]:
a1/a2

array([1.        , 0.66666667, 0.8       , 0.85714286, 0.88888889,
       0.90909091])

In [42]:
a1*a2

array([  1,   6,  20,  42,  72, 110])

In [43]:
a1**a2

array([           1,            8,         1024,       279936,
          134217728, 100000000000])

### Broadcasting

#### Broadcasting mean adding 1 number in all the elements of array

In [44]:
arr = np.array([10,20,30,40,50,60])
arr +10

array([20, 30, 40, 50, 60, 70])

### shalow copy

In [45]:
arr = np.arange(1,21)

In [46]:
slice = arr[:5]
slice*10

array([10, 20, 30, 40, 50])

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### See the example above the orignal array hasn't been changes while we have sliced the array and applied multiplication. This is shallow copy

## Metrics operations

In [48]:
A = np.array([[2,3], [4,5]])
B= np.array([[6,7], [8,9]])
A

array([[2, 3],
       [4, 5]])

In [49]:
A@B 

array([[36, 41],
       [64, 73]])

In [50]:
np.dot(A,B)

array([[36, 41],
       [64, 73]])

In [51]:
# @ or dot is used for multiplication of metrics

In [52]:
A.T

array([[2, 4],
       [3, 5]])

In [53]:
# T is use to take a transpose of metrics

### Stacking

In [54]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,7])

In [57]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7])

In [58]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 7]])

In [59]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 7]])

### Split

In [60]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.vsplit(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [62]:
np.hsplit(arr, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]