In [14]:
import numpy as np

In [15]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]) 

In [16]:
# find if the sum of rows is 45 or not
sum_of_rows = np.sum(s, axis=1)
for i in sum_of_rows:
    if i != 45: 
        print("rows are not valid")
        break
    else: 
        print("rows are valid")

rows are valid
rows are valid
rows are valid
rows are valid
rows are valid
rows are valid
rows are valid
rows are valid
rows are valid


In [17]:
# find if the sum of col is 45 or not
sum_of_col = np.sum(s, axis=1)
for i in sum_of_col:
    if i != 45: 
        print("coulmns are not valid")
        break
    else: 
        print("coulmns are valid")

coulmns are valid
coulmns are valid
coulmns are valid
coulmns are valid
coulmns are valid
coulmns are valid
coulmns are valid
coulmns are valid
coulmns are valid


In [18]:
for i in range(0,9,3):
    for j in range(0,9,3): 
        n= (s[i:i+3, j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [19]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [20]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [21]:
#Find the average age of students.
age = data[0:,0]
avg_age= np.mean(age)
print(f"the average age is {avg_age}")

the average age is 18.4


In [22]:
#Extract Math marks of all students.
math_marks = data[0:, 1]
print(f"Math marks are {math_marks}")

Math marks are [85 92 76 65 90]


In [23]:
#Find the highest Science mark.
science_marks = data[0:,2]
print(f"the highest science marks are  {science_marks.max()}")

the highest science marks are  95


In [24]:
#Get details of the student who scored more than 90 in Math.

higest = data[data[0:, 1] > 90]
higest

array([[19, 92, 88]])

In [25]:
#Increase Math marks of all students by 5.
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [26]:
#Find how many students are younger than 19.
data[data[:, 0] > 19]

array([[20, 95, 85]])

In [27]:
#Calculate the average marks in each subject (column-wise mean).
math_marks_mean = np.mean(data[:, 1])
print(f"math marks mean is {math_marks_mean}")
sci_marks_mean = np.mean(data[:, 2])
print(f"science marks mean is {sci_marks_mean}")

math marks mean is 86.6
science marks mean is 83.2


In [28]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>= 80 )&( data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [31]:
#Replace all Science marks < 75 with 0.
new = data[data[:, 2]< 75 *0]
new

array([], shape=(0, 3), dtype=int64)