In [9]:
import numpy as np

In [2]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
# array slicing you will have  to write the position index of element 
arr[1:6]
# see the example above we sliced the array but remember if you want to slice from 1-6th inddex you will hae to write 1-7th index in ordder to get 6th element of array 

array([12, 13, 14, 15, 16])

In [7]:
arr[1::2]
# The :: is use to skip the elemnt you want like I want to skip 1 element so I wrote ::2 

array([12, 14, 16, 18, 20])

In [10]:
# matix inddex and splicing
met =  np.arange(1,31).reshape(6,5)
met

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
# to findd the row index use below
met[0]

array([1, 2, 3, 4, 5])

In [17]:
# use to find element in exact row andd colmn
met[0,4]

np.int64(5)

In [19]:
# slicing a specific portion 
met[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [35]:
slice= met[3:,5:]
slice

array([], shape=(3, 0), dtype=int64)

In [36]:
# slicing a coulmn 
met[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [37]:
# booleaan indexing

In [39]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [41]:
new_bool = arr[bool_index]
new_bool

array([12, 14, 16, 18, 20])